### ISSUE TITLE
RuntimeError: input and target have different number of elements

### ISSUE THREAD

**Issue by zhaojiayu** [facebookresearch/ELF#46] opened 2017-08-17 08:19 UTC
Hi, 
I met another problem :
log as follow :
```
Traceback (most recent call last):
  File "run.py", line 194, in <module>
    runner.run()
  File "/disk1/benjen/work-space/ELF/rlpytorch/trainer.py", line 179, in run
    self.GC.Run()
  File "/disk1/benjen/work-space/ELF/elf/utils_elf.py", line 254, in Run
    res = self._call(self.infos)
  File "/disk1/benjen/work-space/ELF/elf/utils_elf.py", line 245, in _call
    reply = self._cb[infos.gid](sel, sel_gpu)
  File "run.py", line 178, in train_and_update
    reply = trainer.train(sel, sel_gpu)
  File "/disk1/benjen/work-space/ELF/rlpytorch/trainer.py", line 85, in train
    self.rl_method.run(sel_gpu)
  File "/disk1/benjen/work-space/ELF/rlpytorch/rlmethod_base.py", line 93, in run
    self.update(batch)
  File "/disk1/benjen/work-space/ELF/rlpytorch/rlmethod_common.py", line 124, in update
    value_err = self.value_loss(V, Variable(R))
  File "/usr/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.5/site-packages/torch/nn/modules/loss.py", line 406, in forward
    return F.smooth_l1_loss(input, target, size_average=self.size_average)
  File "/usr/lib/python3.5/site-packages/torch/nn/functional.py", line 811, in smooth_l1_loss
    return _functions.thnn.SmoothL1Loss.apply(input, target, size_average)
  File "/usr/lib/python3.5/site-packages/torch/nn/_functions/thnn/auto.py", line 47, in forward
    output, *ctx.additional_args)
RuntimeError: input and target have different number of elements: input[128 x 1] has 128 elements, while target[128 x 128] has 16384 elements at /pytorch/torch/lib/THCUNN/generic/SmoothL1Criterion.cu:12

```
my command is ：
```
game=./rts/game_MC/game model=actor_critic model_file=./rts/game_MC/model python3 run.py --additional_labels id,last_terminal --num_games 1024 --batchsize 128 --freq_update 50 --fs_opponent 20 --latest_start 500  --latest_start_decay 0.99 --opponent_type AI_SIMPLE --tqdm  --T 20 --gpu 0  
```
i suppose maybe '--batchsize' has problem.

the following is my environment:
os: ubuntu 16.04
nvidia driver version : 375.66    
gcc version: 5.4.0

**Comment by LinZichuan** [comment] 2017-08-18 10:32
+1
It seems to have many problems on Ubuntu. I haven't been able to train yet. Can anybody success to start the training on Ubuntu?

**Comment by gchlodzinski** [comment] 2017-08-18 11:51
I am also having the same problem for some time already.
I played with batchsize parameter a bit but the only thing it changes # of iteration when it crashes and shape of input and target.

**Comment by yuandong-tian** [comment] 2017-08-18 14:50
Hi all, what is your pytorch version?

**Comment by yuandong-tian** [comment] 2017-08-18 15:11
I have reproduced the error with pytorch0.2.0. Fix coming soon.

**Comment by yuandong-tian** [comment] 2017-08-18 15:50
Fixed in dc617b0b0e2826ee1d5d9284ef8b86af51d6d8e2

**Comment by gchlodzinski** [comment] 2017-08-18 17:34
@yuandong-tian thanks for the quick fix, training finally works for me.

**Closed** 2017-08-18 20:26 UTC

**Comment by yuandong-tian** [comment] 2017-08-18 21:39
@gchlodzinski there is another issue. I have fixed it. So please synce to the latest version.

**Comment by gchlodzinski** [comment] 2017-08-18 22:17
@yuandong-tian, Thanks for letting me know. I will update it once I get back to my computer.
